import { ContentGuard } from '@oversightstudio/content-guard/next'
import config from '@payload-config'
import { PasswordGate } from './PasswordGate'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ContentGuard payloadConfig={config} passwordGate={<PasswordGate />}>
          {children}
        </ContentGuard>
      </body>
    </html>
  )
}
